import { Link } from 'react-router-dom';
import { useScrollReveal } from '../hooks/useScrollReveal';
import PageMeta from '../components/PageMeta';
import './LegalPage.css';

export default function PrivacyPolicy() {
  const [contentRef, contentVisible] = useScrollReveal({ threshold: 0.05 });

  return (
    <>
      <PageMeta />
      <div className="legal-page">
        <div className="container">
          <div className="legal-header">
            <h1>Privacy Policy</h1>
            <p className="legal-updated">Last Updated: September 2026</p>
          </div>

          <div className={`legal-content reveal ${contentVisible ? 'in' : ''}`} ref={contentRef}>
            <section>
              <h2>1. Overview</h2>
              <p>XAIVON (Business name: XAIVON) respects the privacy of people who visit our website and communicate with us. This policy explains the types of information we may receive through our website, how we use that information, the service providers that may process it on our behalf, and the choices available to you.</p>
            </section>

            <section>
              <h2>2. Information We Receive</h2>
              <p>When you visit xaivon.com or interact with us, we may receive certain information, which may include:</p>
              <ul>
                <li>Your name, company, email address, and phone number when voluntarily submitted through our contact or assessment forms.</li>
                <li>Information included in an enquiry, assessment request, or communication with us.</li>
                <li>Technical information generated by normal website operation, such as browser type, operating system, and basic network indicators.</li>
                <li>Your consent preferences regarding our use of analytics.</li>
              </ul>
            </section>

            <section>
              <h2>3. How We Use Information</h2>
              <p>We use the information we receive solely for genuine business purposes, specifically to:</p>
              <ul>
                <li>Respond to your enquiries and communications.</li>
                <li>Schedule and conduct assessments.</li>
                <li>Evaluate requested automation opportunities and technical requirements.</li>
                <li>Provide requested services, proposals, or consultations.</li>
                <li>Maintain the security and proper functioning of our website.</li>
                <li>Improve our website operation and service offerings.</li>
                <li>Use consented analytics to understand website usage.</li>
                <li>Communicate with you regarding an active engagement or project.</li>
              </ul>
            </section>

            <section>
              <h2>4. Analytics</h2>
              <p>Our website uses Google Analytics 4 to understand how visitors interact with our content. This analytics implementation is entirely consent-gated. Analytics tracking is only activated if you explicitly provide consent through our cookie consent banner. If you do not consent, we do not load the analytics scripts and no analytics data about your visit is collected by Google Analytics.</p>
            </section>

            <section>
              <h2>5. Service Providers</h2>
              <p>We use trusted service providers to help operate our website and conduct our business operations. For example, our website is hosted on Vercel, and we may use secure email or customer relationship management tools to process enquiries. These providers only process information as necessary to provide their specific services to us.</p>
            </section>

            <section>
              <h2>6. Data Retention</h2>
              <p>Information is retained only as long as needed for legitimate business purposes, such as fulfilling your requests, providing services, communicating regarding an active engagement, or meeting our contractual, security, accounting, or legal obligations, subject to applicable requirements.</p>
            </section>

            <section>
              <h2>7. Your Rights</h2>
              <p>Depending on applicable law and your location, you may have rights concerning your personal information. These may include rights to request access, correction, deletion, restriction, objection, portability, or the withdrawal of previously granted consent regarding your information. To exercise any applicable rights, please contact us using the details below.</p>
            </section>

            <section>
              <h2>8. Security</h2>
              <p>XAIVON uses reasonable administrative, technical, and organizational safeguards appropriate to the information and systems involved to protect against unauthorized access, use, or disclosure. However, no internet transmission or electronic storage is completely secure, and we cannot guarantee absolute security.</p>
            </section>

            <section>
              <h2>9. Changes</h2>
              <p>We may update this Privacy Policy periodically to reflect changes in our practices or legal requirements. When we do, we will revise the "Last Updated" date at the top of this policy.</p>
            </section>

            <section>
              <h2>10. Contact</h2>
              <p>If you have any questions or requests regarding this Privacy Policy or your information, please contact us at:</p>
              <p>XAIVON (Business name: XAIVON)<br /><a href="mailto:raja@xaivon.com">raja@xaivon.com</a><br /><a href="tel:+19175340270">+1 (917) 534-0270</a></p>
              <p>For more information on how you can get in touch with us, please visit our <Link to="/contact">Contact page</Link>. To review or change your cookie preferences, please see our <Link to="/cookie-policy">Cookie Policy</Link>.</p>
            </section>
          </div>
        </div>
      </div>
    </>
  );
}
